fn main() -> anyhow::Result<()> {
    println!("cargo:rerun-if-changed=../../protocol/lib-server.proto");
    println!("cargo:rerun-if-changed=../../protocol/common.proto");
    println!("cargo:rerun-if-changed=../../protocol/server-js.proto");
    tonic_prost_build::configure()
        .build_server(true)
        .file_descriptor_set_path(
            std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap())
                .join("libserver_descriptor.bin"),
        )
        .compile_protos(
            &[
                "../../protocol/lib-server.proto",
                "../../protocol/common.proto",
            ],
            &["../../protocol"],
        )?;
    prost_build::Config::new().compile_protos(
        &[
            "../../protocol/server-js.proto",
            "../../protocol/common.proto",
        ],
        &["../../protocol"],
    )?;
    Ok(())
}
